cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    hong:
      email: hong@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: hong
      password: $2b$12$ZFiMd8/Svdy0H1uc9WPmP.2H/RqZPDS8h4e4M7MY004sZfxD4cen2
    honggyeong:
      email: 07022osc@naver.com
      failed_login_attempts: 0
      logged_in: false
      name: honggyeong
      password: $2b$12$9gmKEF21b13bkbaQES4Wiu4JK6E0Mjbc4cKQ0ZJE5jaJuFzgsh4U.
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: John Smith
      password: $2b$12$VzqC79Haf0zDDudHozzvIO4oDun4.gcOWpgVfhkEWKhl.xuuHhNfa
    jun:
      email: jun@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: jun
      password: $2b$12$ZKNcikknQlm5sM34xtwiUe7e8hXNndj2WoP/2p.qKPq6s3eKoHVJe
    junhyeong:
      email: jjjj@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: junhyeong
      password: $2b$12$1rIsJg.o1zXavPL6pNSTiO6IbeVR37D.g7/IsZ2w6YIoXTCKW7hGm
    nice:
      email: nice@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: nice
      password: $2b$12$u1Hjk8BjeMKY0/gi1aKSWe8PezJ/JegNvwKWgJX9pRv2yMFIYjN2C
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$2h/0mj19qRNPtV835gf0ueejKIo8kugORWL.ZBNZiILQut3LhQbIy
    tue:
      email: tue@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: tue
      password: $2b$12$b12cPAn8ixb5BbLixUPWNeuIe.QJIwNXcfyx35grf3nfDMzc99aIa
preauthorized:
  emails:
  - melsby@gmail.com
