cookie:
  expiry_days: 30
  key: your_secret_key
  name: your_cookie_name
credentials:
  usernames:
    dongum:
      email: dh@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: dong ha
      password: $2b$12$g0NHVsDQSZQCMJ6SW13pAedRPMycmpCC1PbM.YySyJ7ypQGdXylx6
    gh:
      email: gh@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: gh
      password: $2b$12$5Jo9iRFn4G.drcXV8woCkOJqTzJEfpTi3RIN//GRUVIYpGKTGId2S
    hal:
      email: hal@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: hal
      password: $2b$12$20Ch20CGKmlE1YuZmRjxNObZxS.kfn51gOkJCUj962qNVz8UYQzL2
    hi:
      email: hi@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: hi
      password: $2b$12$pAMURhnSCMwN7mImcBEm2uPMFKCL0DsQ6jwk.9cO9tG26psSBA3LK
    hoho:
      email: ho@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: ho
      password: $2b$12$e84jDkcro/R3jnLqvS.iuOwMl7SD0UmgULq618Q1UOVrn2lOmHHY.
    hon:
      email: hon@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: hon
      password: $2b$12$sIAssH8RZioGWMsClnTFiuKRC1G/7yFGAEPvSQE3RjZmkJnyDpOj6
    jw:
      email: jaewon07@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: jaewon
      password: $2b$12$A6rQSDQg9mR8e8CsmTVyQOj0991RvBSiZownv7cqqiC/OyUTg/gx.
    mm:
      email: mm@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: mm
      password: $2b$12$EtQ9lBq64wxCMotJRBimEO4yYTfPenkuqmiceWwBySGlkQlLK3p.i
    oo:
      email: oo@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: oo
      password: $2b$12$cLenhYkk33nr34ou9DhglO9LrwuRlTgDDZj4zgj.S57dx/Pb6.kNe
    user:
      email: user@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: user
      password: $2b$12$VP7LxeFfqvA5aGyjFLij1eK2ecalamZq.OtczPKrByYVwmCttVb8O
    yang:
      email: yy@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: yang
      password: $2b$12$emB98U3sYR7DFQNf6gngNOBeuYrRoWjiQUv5rHkMmReEN5/C3/uXu
    yo:
      email: yo@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: yo
      password: $2b$12$kKtbSt0CIBF5pn871S1KzuBHHjLDnlyc/DOi850JKFmKnePz5pD1W
    your_username:
      email: your_email@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Your Name
      password: $2b$12$i.ekLf6W3O8zsteBmvISDuHcOz2BdXPcxaOZJYHjRbYsJCHKR2RgG
preauthorized:
  emails:
  - your_email@example.com
